[package]
name = "counter"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[lib]
name = "counter"
crate-type = ["cdylib"]

[dependencies]
pd-sys = "0.1.0"
pd-ext = { path = "../../../external" }
pd-ext-macros = { path = "../.." }
