[workspace]

members = [
	"external",
	"macros",
	"examples/hellodsp",
	"examples/helloworld",
	"examples/xfade",
	"examples/counter",
	"examples/complex_counter",
]

[profile.release]
lto = true
panic = "abort"
