[package]
name = "pd-sys"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"
build = false #disable to rebuild

[build-dependencies]
bindgen = "0.49.0"

[features]
default = []
doubleprecision = []
instance = []

