[package]
name = "puredata-external-macros"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[lib]
proc-macro = true


[dependencies]
syn = { version = "0.15.39", features=["full"] }
quote = "0.6.13"
proc-macro2 = "0.4.30"
