[package]
name = "helloworld"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[lib]
name = "helloworld"
crate-type = ["cdylib"]

[dependencies]
pd-sys = { path = "../../../pd-sys/" }
pd-ext = { path = "../../../external" }
pd-ext-macros = { path = "../.." }
