[package]
name = "external"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[dependencies]
puredata-sys = { path = "../puredata-sys" }

[lib]
name = "helloworld"
crate-type = ["cdylib"]
